spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    defer-datasource-initialization: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DEFAULT_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DEFAULT_ADMIN_USERNAME}
    password: ${DEFAULT_ADMIN_PASSWORD}
  servlet:
    multipart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    #sql:
    #init:
    #mode: always
#Cloudinary Properties
cloudinary:
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}
  cloud-name: ${CLOUDINARY_NAME}
logging:
  level:
    org.hibernate.SQL: FALSE
    org.hibernate.orm.jdbc.bind: TRACE
server:
  error:
    include-binding-errors: always
    include-message: always
mail:
  sender: "debugarena@gmail.com"
  receiver: "contact@debugarena.com"
  host: localhost
  port: 1025
  username: ${DEFAULT_EMAIL_SERVER_USERNAME}
  password: ${DEFAULT_EMAIL_SERVER_PASSWORD}

event:
  api:
    baseUrl: "http://localhost:8081"

binding-result-package: org.springframework.validation.BindingResult
